name: build stuff
permissions:
  packages: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"
  push:
    branches:
      - master
    paths:
      - stuff/**
jobs:
  push:
    name: "the-docker-in-question:${{ matrix.stuff }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        stuff:
          - zandebianfix
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./stuff/${{ matrix.stuff }}
          file: ./stuff/${{ matrix.stuff }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ github.repository_owner == 'infinitephantasm' && format('ghcr.io/infinitephantasm/the-docker-in-question:latest', matrix.stuff) || '' }}
